CREATE TABLE [dbo].[PARAMETER](
	[PARAMETER_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARAMETER_NAME] [varchar](255) NOT NULL,
	[PARAMETER_VALUE] [varchar](255) NOT NULL,
	[ISDELETED] [varchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[PARAMETER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE dbo.TASK(
TASK_ID int IDENTITY(1,1) NOT NULL,
TASK_NAME VARCHAR(255) NOT NULL,
TASK_TYPE VARCHAR(25) NOT NULL,
PARAMETER_ID int,
ISDELETED varchar(5) NOT NULL,
CREATEDDATETIME datetime NOT NULL,
MODIFIEDDATETIME datetime NOT NULL,
CONSTRAINT FK_INV_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PARAMETER (PARAMETER_ID),
CONSTRAINT PK_TASK_ID PRIMARY KEY (TASK_ID)
);